import type { UserRole } from "./roles";

/**
 * Catalogue centralisé des permissions (RBAC).
 * Toute vérification d'accès — client ET serveur — doit passer par `hasPermission`.
 */
export const PERMISSIONS = [
  "dashboard:view",
  "system:view",
  "system:manage_profile",
  "system:manage_roles",
  "system:manage_permissions",
  "system:manage_users",
  "system:approve_promotions",
  "system:manage_institutions",
  "system:manage_cafop",
  "system:view_cafop_stats",
  "system:view_cafop_reports",
  "system:manage_apfc",
  "system:convert_csv",
  "system:view_audit_log",
  "system:manage_billing",
  "system:customize_theme",
  "system:view_installation",
  "settings:view",
  "settings:manage_configuration",
  "timetable:view",
  "timetable:manage",
  "attendance:view",
  "attendance:manage",
  "lesson_book:view",
  "lesson_book:manage",
  "lesson_book:approve_access",
  "communication:view",
  "communication:send",
  "grades:view",
  "grades:manage",
  "report_cards:generate",
  "school_record:view",
  "school_record:manage",
  "appointments:view",
  "appointments:manage",
  "premium:view",
  "sms:view",
  "sms:send",
  "inspection:view",
  "inspection:manage",
  "evaluation_grid:view",
  "evaluation_grid:manage",
  "antenna_reports:view",
  "antenna_reports:manage",
  "inspection_reports:view",
  "inspection_reports:manage",
  "institution_report:view",
  "institution_report:manage",
  "activity_reports:view",
  "activity_reports:manage",
  "statistics:class",
  "statistics:institution",
  "statistics:regional",
  "statistics:analytics",
  "statistics:teacher_performance",
  "statistics:pedagogical_effectiveness",
  "recommendations:view",
  "recommendations:manage",
  "role_preview:use",
  "exports:pdf",
  "exports:word",
  "imports:csv",
] as const;

export type Permission = (typeof PERMISSIONS)[number];

/** Domaines fonctionnels, pour la matrice de permissions. */
export const PERMISSION_DOMAINS: { id: string; label: string; permissions: Permission[] }[] = [
  {
    id: "general",
    label: "Général",
    permissions: ["dashboard:view", "system:view", "system:manage_profile"],
  },
  {
    id: "administration",
    label: "Administration système",
    permissions: [
      "system:manage_roles",
      "system:manage_permissions",
      "system:manage_users",
      "system:approve_promotions",
      "system:manage_institutions",
      "system:view_audit_log",
      "system:manage_billing",
      "system:customize_theme",
      "system:view_installation",
      "settings:view",
      "settings:manage_configuration",
    ],
  },
  {
    id: "formation",
    label: "CAFOP & APFC",
    permissions: [
      "system:manage_cafop",
      "system:view_cafop_stats",
      "system:view_cafop_reports",
      "system:manage_apfc",
      "system:convert_csv",
    ],
  },
  {
    id: "vie_scolaire",
    label: "Vie scolaire",
    permissions: [
      "timetable:view",
      "timetable:manage",
      "attendance:view",
      "attendance:manage",
      "lesson_book:view",
      "lesson_book:manage",
      "lesson_book:approve_access",
      "grades:view",
      "grades:manage",
      "report_cards:generate",
      "school_record:view",
      "school_record:manage",
      "premium:view",
    ],
  },
  {
    id: "communication",
    label: "Communication & RDV",
    permissions: [
      "communication:view",
      "communication:send",
      "appointments:view",
      "appointments:manage",
      "sms:view",
      "sms:send",
    ],
  },
  {
    id: "inspection",
    label: "Inspection & Supervision",
    permissions: [
      "inspection:view",
      "inspection:manage",
      "evaluation_grid:view",
      "evaluation_grid:manage",
      "inspection_reports:view",
      "inspection_reports:manage",
      "recommendations:view",
      "recommendations:manage",
    ],
  },
  {
    id: "rapports",
    label: "Rapports & Statistiques",
    permissions: [
      "institution_report:view",
      "institution_report:manage",
      "activity_reports:view",
      "activity_reports:manage",
      "antenna_reports:view",
      "antenna_reports:manage",
      "statistics:class",
      "statistics:institution",
      "statistics:regional",
      "statistics:analytics",
      "statistics:teacher_performance",
      "statistics:pedagogical_effectiveness",
    ],
  },
  {
    id: "outils",
    label: "Outils transverses",
    permissions: ["role_preview:use", "exports:pdf", "exports:word", "imports:csv"],
  },
];

export const PERMISSION_LABELS: Record<Permission, string> = {
  "dashboard:view": "Voir le tableau de bord",
  "system:view": "Accéder à l'espace système",
  "system:manage_profile": "Gérer son profil",
  "system:manage_roles": "Gérer les rôles",
  "system:manage_permissions": "Gérer les habilitations",
  "system:manage_users": "Gérer les comptes utilisateurs",
  "system:approve_promotions": "Approuver les promotions",
  "system:manage_institutions": "Gérer les établissements",
  "system:manage_cafop": "Gérer les centres CAFOP",
  "system:view_cafop_stats": "Voir les statistiques CAFOP",
  "system:view_cafop_reports": "Voir les rapports CAFOP",
  "system:manage_apfc": "Gérer les antennes APFC",
  "system:convert_csv": "Utiliser le convertisseur CSV",
  "system:view_audit_log": "Consulter le journal d'activité",
  "system:manage_billing": "Gérer la facturation",
  "system:customize_theme": "Personnaliser le thème",
  "system:view_installation": "Voir l'installation",
  "settings:view": "Voir la configuration",
  "settings:manage_configuration": "Modifier la configuration",
  "timetable:view": "Voir les emplois du temps",
  "timetable:manage": "Gérer les emplois du temps",
  "attendance:view": "Voir le registre d'appel",
  "attendance:manage": "Faire l'appel",
  "lesson_book:view": "Voir le cahier de texte",
  "lesson_book:manage": "Gérer le cahier de texte",
  "lesson_book:approve_access": "Valider les accès au cahier de texte",
  "communication:view": "Voir les messages",
  "communication:send": "Envoyer des messages",
  "grades:view": "Voir les notes",
  "grades:manage": "Saisir les notes",
  "report_cards:generate": "Générer les bulletins",
  "school_record:view": "Voir le livret scolaire",
  "school_record:manage": "Gérer le livret scolaire",
  "appointments:view": "Voir les rendez-vous",
  "appointments:manage": "Gérer les rendez-vous",
  "premium:view": "Accéder à l'Académie Premium",
  "sms:view": "Voir les alertes SMS",
  "sms:send": "Envoyer des SMS",
  "inspection:view": "Voir les inspections",
  "inspection:manage": "Gérer les inspections",
  "evaluation_grid:view": "Voir les grilles d'évaluation",
  "evaluation_grid:manage": "Gérer les grilles d'évaluation",
  "antenna_reports:view": "Voir les rapports d'antennes",
  "antenna_reports:manage": "Gérer les rapports d'antennes",
  "inspection_reports:view": "Voir les rapports d'inspection",
  "inspection_reports:manage": "Gérer les rapports d'inspection",
  "institution_report:view": "Voir le rapport d'établissement",
  "institution_report:manage": "Gérer le rapport d'établissement",
  "activity_reports:view": "Voir les rapports d'activité",
  "activity_reports:manage": "Gérer les rapports d'activité",
  "statistics:class": "Statistiques par classe",
  "statistics:institution": "Statistiques d'établissement",
  "statistics:regional": "Statistiques régionales",
  "statistics:analytics": "Analytics avancés",
  "statistics:teacher_performance": "Performance des enseignants",
  "statistics:pedagogical_effectiveness": "Efficacité pédagogique",
  "recommendations:view": "Voir les recommandations",
  "recommendations:manage": "Gérer les recommandations",
  "role_preview:use": "Utiliser l'aperçu de rôle",
  "exports:pdf": "Exporter en PDF",
  "exports:word": "Exporter en Word",
  "imports:csv": "Importer des CSV",
};

const ALL: Permission[] = [...PERMISSIONS];

/**
 * Matrice rôle -> permissions. `admin` dispose de tout.
 */
export const ROLE_PERMISSIONS: Record<UserRole, Permission[]> = {
  admin: ALL,
  etablissements_admin: [
    "dashboard:view",
    "system:view",
    "system:manage_profile",
    "system:manage_users",
    "system:manage_institutions",
    "system:convert_csv",
    "settings:view",
    "settings:manage_configuration",
    "timetable:view",
    "timetable:manage",
    "attendance:view",
    "lesson_book:view",
    "communication:view",
    "communication:send",
    "grades:view",
    "report_cards:generate",
    "school_record:view",
    "appointments:view",
    "appointments:manage",
    "sms:view",
    "institution_report:view",
    "institution_report:manage",
    "activity_reports:view",
    "activity_reports:manage",
    "statistics:class",
    "statistics:institution",
    "statistics:analytics",
    "statistics:teacher_performance",
    "statistics:pedagogical_effectiveness",
    "recommendations:view",
    "exports:pdf",
    "exports:word",
    "imports:csv",
    "role_preview:use",
  ],
  cafop_admin: [
    "dashboard:view",
    "system:view",
    "system:manage_profile",
    "system:manage_cafop",
    "system:view_cafop_stats",
    "system:view_cafop_reports",
    "system:convert_csv",
    "settings:view",
    "statistics:analytics",
    "exports:pdf",
    "exports:word",
    "imports:csv",
  ],
  apfc_admin: [
    "dashboard:view",
    "system:view",
    "system:manage_profile",
    "system:manage_apfc",
    "system:convert_csv",
    // Outils de la section « Inspection & Supervision » (qui héberge désormais la page APFC).
    "inspection:view",
    "inspection:manage",
    "evaluation_grid:view",
    "evaluation_grid:manage",
    "inspection_reports:view",
    "inspection_reports:manage",
    "antenna_reports:view",
    "antenna_reports:manage",
    "statistics:analytics",
    "statistics:regional",
    "recommendations:view",
    "exports:pdf",
    "exports:word",
    "imports:csv",
  ],
  drena: [
    "dashboard:view",
    "system:view",
    "system:manage_profile",
    "system:manage_institutions",
    "inspection:view",
    "inspection_reports:view",
    "institution_report:view",
    "activity_reports:view",
    "antenna_reports:view",
    "communication:view",
    "communication:send",
    "appointments:view",
    "statistics:institution",
    "statistics:regional",
    "statistics:analytics",
    "statistics:teacher_performance",
    "statistics:pedagogical_effectiveness",
    "recommendations:view",
    "recommendations:manage",
    "exports:pdf",
    "exports:word",
    "role_preview:use",
  ],
  inspecteur: [
    "dashboard:view",
    "system:view",
    "system:manage_profile",
    "inspection:view",
    "inspection:manage",
    "evaluation_grid:view",
    "evaluation_grid:manage",
    "inspection_reports:view",
    "inspection_reports:manage",
    "recommendations:view",
    "recommendations:manage",
    "lesson_book:view",
    "communication:view",
    "communication:send",
    "appointments:view",
    "appointments:manage",
    "statistics:institution",
    "statistics:teacher_performance",
    "statistics:pedagogical_effectiveness",
    "exports:pdf",
    "exports:word",
  ],
  conseiller_pedagogique: [
    "dashboard:view",
    "system:view",
    "system:manage_profile",
    "inspection:view",
    "evaluation_grid:view",
    "antenna_reports:view",
    "antenna_reports:manage",
    "inspection_reports:view",
    "recommendations:view",
    "recommendations:manage",
    "lesson_book:view",
    "communication:view",
    "communication:send",
    "appointments:view",
    "appointments:manage",
    "statistics:teacher_performance",
    "statistics:pedagogical_effectiveness",
    "exports:pdf",
    "exports:word",
  ],
  chef_antenne: [
    "dashboard:view",
    "system:view",
    "system:manage_profile",
    "antenna_reports:view",
    "antenna_reports:manage",
    "activity_reports:view",
    "activity_reports:manage",
    "recommendations:view",
    "communication:view",
    "communication:send",
    "appointments:view",
    "appointments:manage",
    "statistics:analytics",
    "exports:pdf",
    "exports:word",
  ],
  chef_etablissement: [
    "dashboard:view",
    "system:view",
    "system:manage_profile",
    "system:manage_users",
    "settings:view",
    "settings:manage_configuration",
    "timetable:view",
    "timetable:manage",
    "attendance:view",
    "attendance:manage",
    "lesson_book:view",
    "lesson_book:manage",
    "lesson_book:approve_access",
    "communication:view",
    "communication:send",
    "grades:view",
    "grades:manage",
    "report_cards:generate",
    "school_record:view",
    "school_record:manage",
    "appointments:view",
    "appointments:manage",
    "sms:view",
    "sms:send",
    "inspection:view",
    "institution_report:view",
    "institution_report:manage",
    "activity_reports:view",
    "activity_reports:manage",
    "statistics:class",
    "statistics:institution",
    "statistics:analytics",
    "statistics:teacher_performance",
    "statistics:pedagogical_effectiveness",
    "recommendations:view",
    "recommendations:manage",
    "premium:view",
    "exports:pdf",
    "exports:word",
    "imports:csv",
    "role_preview:use",
  ],
  enseignant: [
    "dashboard:view",
    "system:view",
    "system:manage_profile",
    "timetable:view",
    "attendance:view",
    "attendance:manage",
    "lesson_book:view",
    "lesson_book:manage",
    "communication:view",
    "communication:send",
    "grades:view",
    "grades:manage",
    "report_cards:generate",
    "school_record:view",
    "appointments:view",
    "appointments:manage",
    "statistics:class",
    "premium:view",
    "exports:pdf",
  ],
  educateur: [
    "dashboard:view",
    "system:view",
    "system:manage_profile",
    "timetable:view",
    "attendance:view",
    "attendance:manage",
    "lesson_book:view",
    "communication:view",
    "communication:send",
    "appointments:view",
    "appointments:manage",
    "school_record:view",
    "sms:view",
    "sms:send",
    "statistics:class",
    "exports:pdf",
  ],
  parent: [
    "dashboard:view",
    "system:manage_profile",
    "timetable:view",
    "attendance:view",
    "lesson_book:view",
    "communication:view",
    "communication:send",
    "grades:view",
    "school_record:view",
    "appointments:view",
    "appointments:manage",
    "premium:view",
  ],
  eleve: [
    "dashboard:view",
    "system:manage_profile",
    "timetable:view",
    "attendance:view",
    "lesson_book:view",
    "grades:view",
    "school_record:view",
    "communication:view",
    "appointments:view",
    "premium:view",
  ],
};

/**
 * Vérifie qu'un rôle dispose d'une permission donnée.
 * Surcharges optionnelles : permissions accordées/retirées au niveau utilisateur.
 */
export function hasPermission(
  role: UserRole | null | undefined,
  permission: Permission,
  overrides?: { granted?: Permission[]; revoked?: Permission[] },
): boolean {
  if (!role) return false;
  if (overrides?.revoked?.includes(permission)) return false;
  if (overrides?.granted?.includes(permission)) return true;
  return ROLE_PERMISSIONS[role]?.includes(permission) ?? false;
}

/** Renvoie l'ensemble effectif de permissions d'un rôle. */
export function permissionsForRole(role: UserRole): Permission[] {
  return ROLE_PERMISSIONS[role] ?? [];
}

/** Nombre de permissions par rôle (utile pour la matrice). */
export function permissionCount(role: UserRole): number {
  return ROLE_PERMISSIONS[role]?.length ?? 0;
}
